"""create surat keluar table and update user table

Revision ID: 0adf0356bb89
Revises: d06c0bdb1603
Create Date: 2022-08-24 20:31:21.176243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0adf0356bb89'
down_revision = 'd06c0bdb1603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surat_keluar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomor', sa.String(length=64), nullable=True),
    sa.Column('jenis', sa.String(length=125), nullable=False),
    sa.Column('ringkasan', sa.String(length=255), nullable=False),
    sa.Column('tanggal_dikeluarkan', sa.DateTime(), nullable=True),
    sa.Column('tujuan', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nomor')
    )
    op.add_column('surat_masuk', sa.Column('nomor', sa.String(length=64), nullable=True))
    op.drop_constraint('surat_masuk_no_surat_key', 'surat_masuk', type_='unique')
    op.create_unique_constraint(None, 'surat_masuk', ['nomor'])
    op.drop_column('surat_masuk', 'no_surat')
    op.add_column('user', sa.Column('no_telpon', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'no_telpon')
    op.add_column('surat_masuk', sa.Column('no_surat', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'surat_masuk', type_='unique')
    op.create_unique_constraint('surat_masuk_no_surat_key', 'surat_masuk', ['no_surat'])
    op.drop_column('surat_masuk', 'nomor')
    op.drop_table('surat_keluar')
    # ### end Alembic commands ###
