"""empty message

Revision ID: 20c6f9bae628
Revises: 6b57367dfbf0
Create Date: 2022-09-09 15:52:58.369933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20c6f9bae628'
down_revision = '6b57367dfbf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('daily_activity', 'kegiatan',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('daily_activity', 'tanggal',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('daily_activity', 'deskripsi',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('daily_activity', 'output',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('daily_activity', 'output',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('daily_activity', 'deskripsi',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('daily_activity', 'tanggal',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('daily_activity', 'kegiatan',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###
