"""update user table

Revision ID: 25a9a4067283
Revises: d38d2ea3d09d
Create Date: 2022-08-31 22:12:37.286888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25a9a4067283'
down_revision = 'd38d2ea3d09d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nama', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('bidang', sa.String(length=35), nullable=True))
    op.drop_column('user', 'nama_lengkap')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nama_lengkap', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('user', 'bidang')
    op.drop_column('user', 'nama')
    # ### end Alembic commands ###
