"""update SuratMasuk table

Revision ID: 287bf38591dc
Revises: 4da8e6f72a61
Create Date: 2022-08-23 17:10:22.377835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '287bf38591dc'
down_revision = '4da8e6f72a61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surat_masuk', sa.Column('lampiran', sa.LargeBinary(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surat_masuk', 'lampiran')
    # ### end Alembic commands ###
