"""update user table

Revision ID: 37e998407ff7
Revises: 25a9a4067283
Create Date: 2022-09-01 08:42:39.964337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37e998407ff7'
down_revision = '25a9a4067283'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'bidang')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bidang', sa.VARCHAR(length=35), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
