"""add: daily activity table

Revision ID: 38bf8a7b30f5
Revises: 29e22aa813cb
Create Date: 2022-08-27 23:34:31.194756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38bf8a7b30f5'
down_revision = '29e22aa813cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kegiatan', sa.String(length=64), nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=False),
    sa.Column('output', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_activity')
    # ### end Alembic commands ###
