"""empty message

Revision ID: 3aa7335b9254
Revises: 
Create Date: 2022-11-26 01:21:27.547137

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3aa7335b9254'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('surat_masuk', 'lampiran',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('surat_masuk', 'lampiran',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    # ### end Alembic commands ###
