"""update user table

Revision ID: 3d449c4d8f0c
Revises: 6dd32582a4c2
Create Date: 2022-09-14 11:30:02.060243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d449c4d8f0c'
down_revision = '6dd32582a4c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('foto', sa.LargeBinary(), nullable=True))
    op.drop_column('user', 'foto_profile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('foto_profile', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.drop_column('user', 'foto')
    # ### end Alembic commands ###
