"""update SuratMasuk table

Revision ID: 3f0c0736239e
Revises: ebe3a3ec4245
Create Date: 2022-08-24 10:35:46.414851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f0c0736239e'
down_revision = 'ebe3a3ec4245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surat_masuk', sa.Column('filename', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surat_masuk', 'filename')
    # ### end Alembic commands ###
