"""update surat masuk & surat keluar

Revision ID: 43d0691ed435
Revises: 3d449c4d8f0c
Create Date: 2022-09-14 11:39:29.014272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43d0691ed435'
down_revision = '3d449c4d8f0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surat_keluar', 'nama_file')
    op.drop_column('surat_masuk', 'nama_file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surat_masuk', sa.Column('nama_file', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('surat_keluar', sa.Column('nama_file', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
