"""update surat masuk table

Revision ID: 46e85264c62b
Revises: 63dad5dcc0b7
Create Date: 2022-09-07 09:48:56.148476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46e85264c62b'
down_revision = '63dad5dcc0b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surat_masuk', sa.Column('pesan', sa.Text(), nullable=True))
    op.add_column('surat_masuk', sa.Column('tindak_lanjut', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surat_masuk', 'tindak_lanjut')
    op.drop_column('surat_masuk', 'pesan')
    # ### end Alembic commands ###
