"""surat masuk table

Revision ID: 4da8e6f72a61
Revises: b7bdeecc82ab
Create Date: 2022-08-23 14:56:56.348075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4da8e6f72a61'
down_revision = 'b7bdeecc82ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surat_masuk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('no_surat', sa.String(length=64), nullable=True),
    sa.Column('asal', sa.String(length=125), nullable=False),
    sa.Column('perihal', sa.String(length=255), nullable=False),
    sa.Column('tanggal_terima', sa.DateTime(), nullable=True),
    sa.Column('tujuan', sa.String(length=125), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('no_surat')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('surat_masuk')
    # ### end Alembic commands ###
