"""empty message

Revision ID: 5964bc9c15f6
Revises: b07b4ac8c380
Create Date: 2022-09-08 09:09:48.856524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5964bc9c15f6'
down_revision = 'b07b4ac8c380'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'bidang')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bidang', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
