"""empty message

Revision ID: 5acdaec90660
Revises: b36712876db0
Create Date: 2022-11-10 10:04:44.729938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5acdaec90660'
down_revision = 'b36712876db0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bidang', 'kabid')
    op.drop_column('bidang', 'nip_kabid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bidang', sa.Column('nip_kabid', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('bidang', sa.Column('kabid', sa.VARCHAR(length=85), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
