"""empty message

Revision ID: 6b57367dfbf0
Revises: 5964bc9c15f6
Create Date: 2022-09-09 09:20:02.362092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b57367dfbf0'
down_revision = '5964bc9c15f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kegiatan', sa.String(length=64), nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=False),
    sa.Column('output', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('dailyactivity_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'daily_activity', ['dailyactivity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'dailyactivity_id')
    op.drop_table('daily_activity')
    # ### end Alembic commands ###
