"""update surat masuk & surat keluar table

Revision ID: 6dd32582a4c2
Revises: 20c6f9bae628
Create Date: 2022-09-13 16:46:05.334298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dd32582a4c2'
down_revision = '20c6f9bae628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surat_keluar', sa.Column('perihal', sa.String(length=255), nullable=False))
    op.drop_column('surat_keluar', 'ringkasan')
    op.add_column('surat_masuk', sa.Column('jenis', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surat_masuk', 'jenis')
    op.add_column('surat_keluar', sa.Column('ringkasan', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('surat_keluar', 'perihal')
    # ### end Alembic commands ###
