"""update surat masuk #2

Revision ID: 718dace6df20
Revises: 7a27ef36be5e
Create Date: 2022-08-31 09:04:23.926997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '718dace6df20'
down_revision = '7a27ef36be5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surat_masuk', sa.Column('tanggal_surat', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surat_masuk', 'tanggal_surat')
    # ### end Alembic commands ###
