"""update surat_balasan table

Revision ID: 78642492a944
Revises: 9f8a0d64f51a
Create Date: 2022-09-15 19:06:55.881489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78642492a944'
down_revision = '9f8a0d64f51a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surat_balasan', sa.Column('kepala', sa.Text(), nullable=False))
    op.add_column('surat_balasan', sa.Column('penutup', sa.Text(), nullable=False))
    op.drop_column('surat_balasan', 'footer')
    op.drop_column('surat_balasan', 'header')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surat_balasan', sa.Column('header', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('surat_balasan', sa.Column('footer', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('surat_balasan', 'penutup')
    op.drop_column('surat_balasan', 'kepala')
    # ### end Alembic commands ###
