"""update surat masuk

Revision ID: 7a27ef36be5e
Revises: a597d923e6b7
Create Date: 2022-08-31 08:57:05.292959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a27ef36be5e'
down_revision = 'a597d923e6b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surat_masuk', 'tujuan')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surat_masuk', sa.Column('tujuan', sa.VARCHAR(length=125), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
