"""empty message

Revision ID: 811d94144ae0
Revises: 
Create Date: 2022-11-12 23:51:34.608477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '811d94144ae0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bidang_subbidang_id_fkey', 'bidang', type_='foreignkey')
    op.drop_column('bidang', 'subbidang_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bidang', sa.Column('subbidang_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('bidang_subbidang_id_fkey', 'bidang', 'sub_bidang', ['subbidang_id'], ['id'])
    # ### end Alembic commands ###
