"""fix typos

Revision ID: 97336e0a87bd
Revises: a96f324e6fd1
Create Date: 2022-11-01 08:21:48.653951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97336e0a87bd'
down_revision = 'a96f324e6fd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('informasi_badan', sa.Column('nip_kepala', sa.Integer(), nullable=True))
    op.drop_column('informasi_badan', 'nim_kepala')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('informasi_badan', sa.Column('nim_kepala', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('informasi_badan', 'nip_kepala')
    # ### end Alembic commands ###
