"""update surat masuk #3

Revision ID: 97f777ced4a4
Revises: 718dace6df20
Create Date: 2022-08-31 09:13:22.416302

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '97f777ced4a4'
down_revision = '718dace6df20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surat_masuk', sa.Column('tanggal_diterima', sa.DateTime(), nullable=True))
    op.drop_column('surat_masuk', 'tanggal_terima')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surat_masuk', sa.Column('tanggal_terima', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('surat_masuk', 'tanggal_diterima')
    # ### end Alembic commands ###
