"""init

Revision ID: a2b2cb8dc19a
Revises: 
Create Date: 2022-11-02 09:41:27.648346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2b2cb8dc19a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=True),
    sa.Column('waktu', sa.String(length=50), nullable=True),
    sa.Column('agenda', sa.String(length=225), nullable=False),
    sa.Column('tempat', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bidang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode', sa.String(length=50), nullable=True),
    sa.Column('nama', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disposisi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=50), nullable=True),
    sa.Column('nama', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('informasi_badan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=200), nullable=True),
    sa.Column('kepala', sa.String(length=150), nullable=True),
    sa.Column('nip_kaban', sa.String(length=100), nullable=True),
    sa.Column('alamat', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('telpon', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_role_default'), 'role', ['default'], unique=False)
    op.create_table('surat_balasan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kepala', sa.Text(), nullable=False),
    sa.Column('isi', sa.Text(), nullable=False),
    sa.Column('penutup', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surat_keluar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomor', sa.String(length=64), nullable=True),
    sa.Column('jenis', sa.String(length=125), nullable=False),
    sa.Column('perihal', sa.String(length=255), nullable=False),
    sa.Column('tanggal_dikeluarkan', sa.DateTime(), nullable=True),
    sa.Column('tujuan', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('lampiran', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surat_masuk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomor', sa.String(length=64), nullable=True),
    sa.Column('asal', sa.String(length=125), nullable=False),
    sa.Column('perihal', sa.Text(), nullable=False),
    sa.Column('jenis', sa.String(length=50), nullable=True),
    sa.Column('tanggal_surat', sa.DateTime(), nullable=True),
    sa.Column('tanggal_diterima', sa.DateTime(), nullable=True),
    sa.Column('rak', sa.String(), nullable=False),
    sa.Column('lampiran', sa.LargeBinary(), nullable=False),
    sa.Column('disposisi_ke', sa.String(length=50), nullable=True),
    sa.Column('pesan', sa.Text(), nullable=True),
    sa.Column('dilihat', sa.Boolean(), nullable=True),
    sa.Column('tindak_lanjut', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=120), nullable=True),
    sa.Column('nama', sa.String(length=50), nullable=True),
    sa.Column('jabatan', sa.String(length=35), nullable=True),
    sa.Column('no_telpon', sa.String(length=100), nullable=True),
    sa.Column('foto', sa.LargeBinary(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('bidang_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bidang_id'], ['bidang.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('daily_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kegiatan', sa.String(length=64), nullable=True),
    sa.Column('tanggal', sa.DateTime(), nullable=True),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('output', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_activity')
    op.drop_table('user')
    op.drop_table('surat_masuk')
    op.drop_table('surat_keluar')
    op.drop_table('surat_balasan')
    op.drop_index(op.f('ix_role_default'), table_name='role')
    op.drop_table('role')
    op.drop_table('informasi_badan')
    op.drop_table('disposisi')
    op.drop_table('bidang')
    op.drop_table('agenda')
    # ### end Alembic commands ###
