"""add nim_kepala rows

Revision ID: a96f324e6fd1
Revises: cf246ea3f3ef
Create Date: 2022-11-01 08:14:37.872529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a96f324e6fd1'
down_revision = 'cf246ea3f3ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('informasi_badan', sa.Column('nim_kepala', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('informasi_badan', 'nim_kepala')
    # ### end Alembic commands ###
