"""empty message

Revision ID: b07b4ac8c380
Revises: 46e85264c62b
Create Date: 2022-09-08 09:04:14.259584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b07b4ac8c380'
down_revision = '46e85264c62b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bidang', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'bidang')
    # ### end Alembic commands ###
