"""create surat_balasan table


Revision ID: b7671625abf8
Revises: 43d0691ed435
Create Date: 2022-09-15 16:45:12.395449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7671625abf8'
down_revision = '43d0691ed435'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surat_balasan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('header', sa.Text(), nullable=False),
    sa.Column('isi', sa.Text(), nullable=False),
    sa.Column('footer', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('surat_balasan')
    # ### end Alembic commands ###
