"""empty message

Revision ID: c7aa9563877c
Revises: fd08b58e2839
Create Date: 2022-10-12 08:25:50.074562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7aa9563877c'
down_revision = 'fd08b58e2839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bidang', sa.Column('kode', sa.String(length=50), nullable=True))
    op.drop_column('bidang', 'alias')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bidang', sa.Column('alias', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('bidang', 'kode')
    # ### end Alembic commands ###
