"""add alamat rows

Revision ID: cf246ea3f3ef
Revises: e8598b65ca78
Create Date: 2022-11-01 07:55:19.606687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf246ea3f3ef'
down_revision = 'e8598b65ca78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('informasi_badan', sa.Column('alamat', sa.String(length=200), nullable=True))
    op.alter_column('informasi_badan', 'nama',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('informasi_badan', 'kepala',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('informasi_badan', 'kepala',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('informasi_badan', 'nama',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_column('informasi_badan', 'alamat')
    # ### end Alembic commands ###
