"""update surat keluar tabel

Revision ID: d01d718b5a08
Revises: 0adf0356bb89
Create Date: 2022-08-24 22:16:29.703993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd01d718b5a08'
down_revision = '0adf0356bb89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surat_keluar', sa.Column('lampiran', sa.LargeBinary(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surat_keluar', 'lampiran')
    # ### end Alembic commands ###
