"""update SuratMasuk table

Revision ID: d06c0bdb1603
Revises: 3f0c0736239e
Create Date: 2022-08-24 11:47:26.513114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd06c0bdb1603'
down_revision = '3f0c0736239e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surat_masuk', sa.Column('nama_file', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surat_masuk', 'nama_file')
    # ### end Alembic commands ###
