"""update user profile

Revision ID: df613c0710ba
Revises: 3f3313ef7f64
Create Date: 2022-08-08 09:56:35.927120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df613c0710ba'
down_revision = '3f3313ef7f64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nama_lengkap', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('jabatan', sa.String(length=35), nullable=True))
    op.add_column('user', sa.Column('foto_profile', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'foto_profile')
    op.drop_column('user', 'jabatan')
    op.drop_column('user', 'nama_lengkap')
    # ### end Alembic commands ###
