"""fix typos

Revision ID: df6423d5717a
Revises: 97336e0a87bd
Create Date: 2022-11-01 08:27:45.997930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df6423d5717a'
down_revision = '97336e0a87bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('informasi_badan', sa.Column('nip_kaban', sa.String(length=100), nullable=True))
    op.drop_column('informasi_badan', 'nip_kepala')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('informasi_badan', sa.Column('nip_kepala', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('informasi_badan', 'nip_kaban')
    # ### end Alembic commands ###
