"""add informasi badan table

Revision ID: e8598b65ca78
Revises: 5e1cb2eae9fa
Create Date: 2022-10-31 07:30:02.193749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8598b65ca78'
down_revision = '5e1cb2eae9fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('informasi_badan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=200), nullable=False),
    sa.Column('kepala', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('telpon', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('informasi_badan')
    # ### end Alembic commands ###
