"""empty message

Revision ID: eb788d086cd9
Revises: 78642492a944
Create Date: 2022-09-26 18:24:52.390919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb788d086cd9'
down_revision = '78642492a944'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_activity', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'daily_activity', 'user', ['user_id'], ['id'])
    op.drop_constraint('user_dailyactivity_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'dailyactivity_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('dailyactivity_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_dailyactivity_id_fkey', 'user', 'daily_activity', ['dailyactivity_id'], ['id'])
    op.drop_constraint(None, 'daily_activity', type_='foreignkey')
    op.drop_column('daily_activity', 'user_id')
    # ### end Alembic commands ###
