"""empty message

Revision ID: f503e051a071
Revises: eb788d086cd9
Create Date: 2022-09-29 07:57:06.456193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f503e051a071'
down_revision = 'eb788d086cd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('surat_balasan_surat_masuk_id_fkey', 'surat_balasan', type_='foreignkey')
    op.drop_column('surat_balasan', 'surat_masuk_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surat_balasan', sa.Column('surat_masuk_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('surat_balasan_surat_masuk_id_fkey', 'surat_balasan', 'surat_masuk', ['surat_masuk_id'], ['id'])
    # ### end Alembic commands ###
