"""empty message

Revision ID: f5c1cfd991cc
Revises: f503e051a071
Create Date: 2022-10-05 08:24:17.204927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5c1cfd991cc'
down_revision = 'f503e051a071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surat_masuk', sa.Column('rak', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surat_masuk', 'rak')
    # ### end Alembic commands ###
