"""empty message

Revision ID: fbd4f45bc562
Revises: 131e77ff03b2
Create Date: 2022-11-10 08:42:38.275654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbd4f45bc562'
down_revision = '131e77ff03b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bidang', sa.Column('kasubid', sa.String(length=85), nullable=True))
    op.add_column('bidang', sa.Column('nip_kasubid', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bidang', 'nip_kasubid')
    op.drop_column('bidang', 'kasubid')
    # ### end Alembic commands ###
