"""empty message

Revision ID: fd504580b89c
Revises: 3aa7335b9254
Create Date: 2022-11-26 01:39:26.815346

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fd504580b89c'
down_revision = '3aa7335b9254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('surat_masuk', 'lampiran',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('surat_masuk', 'lampiran',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    # ### end Alembic commands ###
